/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzgc_jniface_FaceFunction */

#ifndef _Included_com_hzgc_jniface_FaceFunction
#define _Included_com_hzgc_jniface_FaceFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzgc_jniface_FaceFunction_init
  (JNIEnv *, jclass);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    initThreadNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_hzgc_jniface_FaceFunction_initThreadNum
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    bigPictureCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_bigPictureCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    personCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_personCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    carCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_carCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceAndPersonCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceAndPersonCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceAndCarCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceAndCarCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    personAndCarCheck
 * Signature: ([BLjava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_personAndCarCheck
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceFeatureExtract
 * Signature: ([BLjava/lang/String;)Lcom/hzgc/jniface/FaceAttribute;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceFeatureExtract
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceCompareBit
 * Signature: ([[B[[BI)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceCompareBit
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

/*
 * Class:     com_hzgc_jniface_FaceFunction
 * Method:    faceCompareFloat
 * Signature: ([[F[[FI)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_hzgc_jniface_FaceFunction_faceCompareFloat
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
